aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

jobs:
  testing:
    docker:
      - image : circleci/node:14
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - run: yarn check --integrity
      - save-cache: *save-cache
      - run: yarn audit-ci --moderate
      - run: yarn lint
      - run: yarn test --maxWorkers=2


workflows:
  version: 2
  build:
    jobs:
      - testing

branches:
  only:
    - master
